version: '3.8'

volumes:
  couchbase-data:

services:
  couchbase:
    image: couchbase:community
    container_name: ${COUCHBASE_CONTAINER_NAME}
    ports:
      - "8091-8096:8091-8096" # Web UI, N1QL, and other DB services
      - "11210:11210"         # SDK port
    environment:
      - COUCHBASE_ADMINISTRATOR_USERNAME=${COUCHBASE_USER}
      - COUCHBASE_ADMINISTRATOR_PASSWORD=${COUCHBASE_PASSWORD}
    volumes:
      - couchbase-data:/opt/couchbase/var

  couchbase-init:
    image: alpine:latest
    container_name: ${COUCHBASE_INIT_CONTAINER_NAME}
    depends_on:
      - couchbase
    volumes:
      - ./couchbase/init.sh:/init.sh
    entrypoint: ["/bin/sh", "/init.sh"]
    environment:
      - COUCHBASE_HOST=${COUCHBASE_HOST}
      - COUCHBASE_USER=${COUCHBASE_USER}
      - COUCHBASE_PASSWORD=${COUCHBASE_PASSWORD}
      - COUCHBASE_BUCKET=${COUCHBASE_BUCKET}

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: ${ZOOKEEPER_CONTAINER_NAME}
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: ${KAFKA_CONTAINER_NAME}
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: ${ZOOKEEPER_CONTAINER_NAME}:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://${MESSAGE_BROKER_HOST}
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kowl:
    image: redpandadata/console:latest
    container_name: ${KOWL_CONTAINER_NAME}
    ports:
      - "8080:8080"
    environment:
      - KAFKA_BROKERS=${MESSAGE_BROKER_HOST}
    depends_on:
      - kafka

  thermostat:
    build:
      context: ./thermostat
    container_name: ${THERMOSTAT_CONTAINER_NAME}
    depends_on:
      - kafka
    environment:
      - DEVICE_ID=Living_Room
      - MESSAGE_BROKER_HOST=${MESSAGE_BROKER_HOST}
      - MESSAGE_BROKER_TOPIC=${MESSAGE_BROKER_TOPIC}

  thermostat_2:
    build:
      context: ./thermostat
    container_name: ${THERMOSTAT_2_CONTAINER_NAME}
    depends_on:
      - kafka
    environment:
      - DEVICE_ID=Garage
      - MESSAGE_BROKER_HOST=${MESSAGE_BROKER_HOST}
      - MESSAGE_BROKER_TOPIC=${MESSAGE_BROKER_TOPIC}

  iot-manager:
    build:
      context: ./iot-manager
    container_name: ${IOT_MANAGER_CONTAINER_NAME}
    depends_on:
      - kafka
      - couchbase
      - couchbase-init
    environment:
      - MESSAGE_BROKER_HOST=${MESSAGE_BROKER_HOST}
      - MESSAGE_BROKER_TOPIC=${MESSAGE_BROKER_TOPIC}
      - COUCHBASE_HOST=${COUCHBASE_HOST}
      - COUCHBASE_USER=${COUCHBASE_USER}
      - COUCHBASE_PASSWORD=${COUCHBASE_PASSWORD}
      - COUCHBASE_BUCKET=${COUCHBASE_BUCKET}

  ui:
    build:
      context: ./ui
    container_name: ${UI_CONTAINER_NAME}
    ports:
      - "3000:3000"
    depends_on:
      - couchbase

  api:
    build:
      context: ./api
    container_name: ${API_CONTAINER_NAME}
    ports:
      - "4000:4000"
    depends_on:
      - couchbase
    environment:
      - COUCHBASE_HOST=${COUCHBASE_HOST}
      - COUCHBASE_USER=${COUCHBASE_USER}
      - COUCHBASE_PASSWORD=${COUCHBASE_PASSWORD}
      - COUCHBASE_BUCKET=${COUCHBASE_BUCKET}

  test:
    build:
      context: ./test
    container_name: ${TEST_CONTAINER_NAME}
    ports:
      - "5000:5000"
    depends_on:
      - couchbase
      - kafka
      - iot-manager
      #- api
    environment:
      - API_HOST=${API_CONTAINER_NAME}
