version: '3.8'

volumes:
  couchbase-data:

services:
  couchbase:
    image: couchbase:community
    container_name: couchbase
    ports:
      - "8091-8096:8091-8096" # Web UI, N1QL, and other DB services
      - "11210:11210"         # SDK port
    environment:
      - COUCHBASE_ADMINISTRATOR_USERNAME=admin
      - COUCHBASE_ADMINISTRATOR_PASSWORD=password
    volumes:
      - couchbase-data:/opt/couchbase/var

  couchbase-init:
    image: alpine:latest
    container_name: couchbase-init
    depends_on:
      - couchbase
    volumes:
      - ./couchbase/init.sh:/init.sh
    entrypoint: ["/bin/sh", "/init.sh"]

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  thermostat:
    build:
      context: ./thermostat
    container_name: thermostat
    depends_on:
      - kafka
    environment:
      - MESSAGE_BROKER=kafka:9092
      - DEVICE_ID=Living_Room

  thermostat_2:
    build:
      context: ./thermostat
    container_name: thermostat_2
    depends_on:
      - kafka
    environment:
      - MESSAGE_BROKER=kafka:9092
      - DEVICE_ID=Garage

  iot-manager:
    build:
      context: ./iot-manager
    container_name: iot-manager
    depends_on:
      - kafka
      - couchbase
      - couchbase-init
    environment:
      - MESSAGE_BROKER=kafka:9092

  ui:
    build:
      context: ./ui
    container_name: ui
    ports:
      - "3000:3000"
    depends_on:
      - couchbase
    environment:
      - COUCHBASE_HOST=couchbase
      - COUCHBASE_USER=admin
      - COUCHBASE_PASSWORD=password
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:4000

  api:
    build:
      context: ./api
    container_name: api
    ports:
      - "4000:4000"
    depends_on:
      - couchbase
    environment:
      - COUCHBASE_HOST=couchbase
      - COUCHBASE_USER=admin
      - COUCHBASE_PASSWORD=password

