version: '3.8'

volumes:
  couchbase-data:
  influxdb:
  grafana:

services:
  couchbase:
    image: couchbase:community
    container_name: ${COUCHBASE_CONTAINER_NAME}
    ports:
      - "8091-8096:8091-8096" # Web UI, N1QL, and other DB services
      - "11210:11210"         # SDK port
    environment:
      - COUCHBASE_ADMINISTRATOR_USERNAME=${COUCHBASE_USER}
      - COUCHBASE_ADMINISTRATOR_PASSWORD=${COUCHBASE_PASSWORD}
    volumes:
      - couchbase-data:/opt/couchbase/var

  couchbase-init:
    image: alpine:latest
    container_name: ${COUCHBASE_INIT_CONTAINER_NAME}
    depends_on:
      - couchbase
    volumes:
      - ./couchbase/init.sh:/init.sh
    entrypoint: ["/bin/sh", "/init.sh"]
    environment:
      - COUCHBASE_HOST=${COUCHBASE_HOST}
      - COUCHBASE_USER=${COUCHBASE_USER}
      - COUCHBASE_PASSWORD=${COUCHBASE_PASSWORD}
      - COUCHBASE_BUCKET=${COUCHBASE_BUCKET}

  zookeeper:
    image: bitnami/zookeeper:3.9
    container_name: ${ZOOKEEPER_CONTAINER_NAME}
    ports:
      - "2181:2181"
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: bitnami/kafka:3.4
    container_name: ${KAFKA_CONTAINER_NAME}
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: ${ZOOKEEPER_CONTAINER_NAME}:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://${MESSAGE_BROKER_HOST}
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CFG_NUM_PARTITIONS: 2
      KAFKA_CREATE_TOPICS: "${MESSAGE_BROKER_TOPIC}:2:1"

  kowl:
    image: redpandadata/console:latest
    container_name: ${KOWL_CONTAINER_NAME}
    ports:
      - "8080:8080"
    environment:
      - KAFKA_BROKERS=${MESSAGE_BROKER_HOST}
    depends_on:
      - kafka

  sensor:
    build:
      context: ./sensor
    container_name: ${SENSOR_CONTAINER_NAME}
    ports:
      - "5001:5001"
    depends_on:
      - kafka
    environment:
      - DEVICE_ID=Living_Room
      - MESSAGE_BROKER_HOST=${MESSAGE_BROKER_HOST}
      - MESSAGE_BROKER_TOPIC=${MESSAGE_BROKER_TOPIC}
      - TELEMETRY_INTERVAL=1000 # Set to 0 for no telemetry
      - PORT=5001
      - SERVICE_STATUS=stopped # Set to 'stopped' to disable telemetry, set to 'started' to enable

  sensor_2:
    build:
      context: ./sensor
    container_name: ${SENSOR_2_CONTAINER_NAME}
    ports:
      - "5002:5002"
    depends_on:
      - kafka
    environment:
      - DEVICE_ID=Garage
      - MESSAGE_BROKER_HOST=${MESSAGE_BROKER_HOST}
      - MESSAGE_BROKER_TOPIC=${MESSAGE_BROKER_TOPIC}
      - TELEMETRY_INTERVAL=1000 # Set to 0 for no telemetry
      - PORT=5002
      - SERVICE_STATUS=stopped # Set to 'stopped' to disable telemetry, set to 'started' to enable

  iot-manager:
    build:
      context: ./iot-manager
    container_name: ${IOT_MANAGER_CONTAINER_NAME}
    ports:
      - "6000:6000"
    depends_on:
      - kafka
      - couchbase
      - couchbase-init
    environment:
      - MESSAGE_BROKER_HOST=${MESSAGE_BROKER_HOST}
      - MESSAGE_BROKER_TOPIC=${MESSAGE_BROKER_TOPIC}
      - COUCHBASE_HOST=${COUCHBASE_HOST}
      - COUCHBASE_USER=${COUCHBASE_USER}
      - COUCHBASE_PASSWORD=${COUCHBASE_PASSWORD}
      - COUCHBASE_BUCKET=${COUCHBASE_BUCKET}
      - PORT=6000
      - SERVICE_STATUS=stopped # Set to 'stopped' to disable consuming by default, set to 'started' to enable
